### ISSUE TITLE
Issues with multiple excludes and regexp

### ISSUE THREAD

**Issue by andreassolberg** [custom-cards/flex-table-card#1] opened 2018-12-28 20:03 UTC
This does not work:

```
          exclude:
            - light\.fibaro.*
            - light.group_2
```

When I comment out the second line, it works:
```
          exclude:
            - light\.fibaro.*
            # - light.group_2
```

From the docs, multiple excludes should be allowed in a list, right? And the format is regexp.

**Comment by daringer** [comment] 2019-01-01 08:17
hmmm, feels like a bug, let me check that

**Comment by daringer** [comment] 2019-01-12 09:32
more than just a bug, simply messy code; fixed and re-worked regex stuff. Would be great if you could check, if it works for you as expected.

generally you can omit any `*` in the excludes, as _any_ match will exclude the entity from the entity list.

**Comment by daringer** [comment] 2019-01-19 23:34
@andreassolberg is this ok for you as this works right now, would close this issue then...

**Comment by daringer** [comment] 2019-03-09 19:02
hope the issue is resolved for you, feel free to re-open it if it's not the case
closing...

**Closed by daringer** 2019-03-09 19:02 UTC
Labels: bug
