### ISSUE TITLE
Sort only takes into consideration the first digit

### ISSUE THREAD

**Issue by bbbenji** [custom-cards/flex-table-card#6] opened 2019-02-18 17:33 UTC
I am displaying a list of entities and their states and sorting by state. Whenever an entity hits 2 digits, it seems that this card only takes the first digit into account for sorting.

![screenshot_20190218_182921](https://user-images.githubusercontent.com/1678118/52967720-369a0b00-33ab-11e9-87f9-a5160ac08c03.png)

As soon as that first entity hit a state of 9, it popped to the bottom of the list.

**config:**
```
type: 'custom:flex-table-card'
sort_by: state+
title: ZTM
entities:
  include: sensor.ztm*
columns:
  - attr: friendly_name
    name: Number
  - prop: state
    name: Time

```

**Comment by daringer** [comment] 2019-03-09 18:53
I believe this is a data-type issue. Means you have to make sure that the data is properly converted to a number, if something like this is the case. This depends where your data is coming from and how it is represented there.

To solve this you can make use of `modify` to parse the data to the designated data-type, in this case I would propose something like this:
```
...
columns:
  - prop: state
    name: Time
    modify: parseFloat(x)
```
Now sort_by should work as expected, take a look into issue #7 to see another similar example.

**Comment by sickidolderivative** [comment] 2019-03-10 09:59
I can confirm the bug is still present in version 0.5.0

**Comment by sickidolderivative** [comment] 2019-03-10 12:49
I now have hard time getting proper number formatting with parseFloat(). Using .toFixed(3) results in bad sorting again. I tried adding and hiding a column for sorting purposes but then it turned out hidden: true does not work properly. It hides column title, but does not hide its values. 

Nevertheless, I really appreciate your work. It's a really useful card that you've made.

**Comment by daringer** [comment] 2019-03-10 15:00
oh no, this is obviously a bug, but can likely be easy fixed, let's see if I can solve this this evening.
Despite that if you would like to use toFixed() the number is coverted to a string again, thus not numerically sortable, other sorting mechanisms (i.e., table viewer tools, fileexplorer) usually implement a "natural" sorting instead of the formal sorting applied here, this might be a solution also to avoid this whole hassle.

In the meantime the best way would really be the hidden flag, looks like I broke during the recent feature-hunt commits, but should be easy... will keep you updated....

**Comment by daringer** [comment] 2019-03-10 15:12
2 lines fix, couldn't resist.
thanks for pointing this out, hopefully I did not introduce a new bug, 
but `hidden: true` at least will hide the header and the contents again.

**Comment by sickidolderivative** [comment] 2019-03-10 15:28
Now it’s perfect. Glad it was a simple fix. Thanks again!

**Comment by daringer** [comment] 2019-03-10 15:41
Then I'll close this issue, don't hesitate to find new bugs :D

**Closed by daringer** 2019-03-10 15:41 UTC
Labels: bug, fix_to_be_verified
