### ISSUE TITLE
Hacs install lists type as module, should be js

### ISSUE THREAD

**Issue by mdegat01** [custom-cards/flex-table-card#22] opened 2020-03-07 20:51 UTC
When looking at this component in HACS it says to list the type as module when including it in the list of resources in the yaml. This doesn't work though, it only works when type is js. It says the correct type in the readme of this repo but the HACS guide needs to be updated to match

**Comment by daringer** [comment] 2020-03-07 23:31
weird, I cannot confirm, that the docs (listing) in HACS is wrong, for me it show this:

![image](https://user-images.githubusercontent.com/2056020/76153855-bd16ad00-60d2-11ea-8c71-345fcd7e742b.png)

Looks good for me compared to the [README.md](https://github.com/custom-cards/flex-table-card/blob/master/README.md). `type: js` and  `url: <url>` both are there.

Anyways it's the default description there, urgently need to create `info.md` and `hacs.json` inside the repo to improve the docs/presentation through HACS. 
thanks for the hint

**Comment by daringer** [comment] 2020-03-08 01:55
Updated the necessary files. The HACS page now provides a basic overview and examples. The installation/configuration entry part of the page is anyways not editable by me, but as said, looks good now, at least for me...

**Comment by mdegat01** [comment] 2020-03-08 02:13
That's so strange! I see your updates, when I open it in HACS I see all the config details now like in the readme (looks great btw, way more details, thanks!). But yet at the bottom I still see this
![Screenshot_20200307-210654](https://user-images.githubusercontent.com/2037026/76155274-d0684f00-60b7-11ea-9c84-b2f970b952b3.png)
I don't really know how to explain this discrepancy but it's still there for me. HACS still seems to think it's a module. If it helps your add-on is listed as a plug-in for me and I have only ever installed and updated it through HACS. Is there maybe a special file HACS wants for that bottom part?

**Comment by mdegat01** [comment] 2020-03-08 02:23
Oh wait, maybe its due to the HACS update? I'm running 0.22.3 version of HACS.  0.22 was a pretty significant update and one of the things was that they deprecated the /community_plugin endpoint and instead ask you to use /hacsfiles.  It looks like in your screenshot it still says /community_plugin so perhaps this was something to do with the 0.22 update?

**Comment by daringer** [comment] 2020-03-08 02:37
Well good hint, I was indeed still on `0.20.3` with HACS, but nothing changed on my side, and yes it's also listed in the *plugins* category. Strange stuff. Maybe pinging @ludeeus might help, anyways will try to catch him tomorrow on discord... 

last straws: 
* did you reload several times? 
* reloaded during *cache disabled* checked, inside the network tab inside the developer tools? 
* if this is not pulled content, then the issue might be inside your HACS data-storage locally?

**Comment by mdegat01** [comment] 2020-03-08 18:40
Definitely reloaded a number of times and just now tried viewing it in both private window as well as specifically reloading with cache disabled in dev tools, no change in behavior for me.

For my local HACS, here's what I have in my hacs.repositories file for flex-table-card:
```
"156292058": {
  "authors": [],
  "category": "plugin",
  "description": "Highly Flexible Lovelace Card - arbitrary contents/columns/rows, regex matched, perfect to show appdaemon created content and anything breaking out of the entity_id + attributes concept",
  "downloads": null,
  "first_install": true,
  "full_name": "custom-cards/flex-table-card",
  "hide": false,
  "installed": true,
  "installed_commit": "5552c08",
  "last_commit": "74d4223",
  "last_release_tag": null,
  "last_updated": "2020-03-08T03:24:04Z",
  "name": "flex-table-card",
  "new": false,
  "repository_manifest": {
    "content_in_root": true,
    "filename": "flex-table-card.js",
    "name": "Flex Table - Highly customizable, Data visualization"
  },
  "selected_tag": null,
  "show_beta": false,
  "stars": 31,
  "topics": [
    "data-table",
    "data-visualization",
    "flexible-table",
    "high-configurability",
    "home-automation",
    "homeassistant",
    "javascript",
    "lovelace",
    "single-file",
    "table-visualization"
  ],
  "version_installed": null
}
```
Does that look right to you?  I don't see module mentioned anywhere in that so nothing is jumping out at me but I'm also not very familiar with this file.

Here's what's in my hacs.installed file for flex-table-card:
```
"custom-cards/flex-table-card": {
  "version_type": "commit",
  "version_installed": "37eb2ce",
  "version_available": "37eb2ce"
}
```
One odd thing here is that version info is many commits ago.  I am currently running version  74d4223 which is the latest.  I'm not sure why that's not reflected in this file but looking around that's true for pretty much everything I installed from HACS.  Everything seems to show the version I installed it at in this file, not the current version I'm actually running.  Maybe that's weird?  I don't really have anything to compare it to so I'm not sure.

**Comment by daringer** [comment] 2020-03-08 22:13
These jsons seem to be fully generated by HACS, although they look "realistic", nevertheless I guess we'll have to address this directly to HACS. 
But wait, now it gets funny: just checked some other plugins (custom-cards), I counted 5 using `type: js` and 6 using `type: component`. So isn't this suspicious? Is `type: component` maybe actually correct, so it's a feature not a bug...

Checked the official lovelace-ui documentation and surprise: I spread the wrong `type: js`, because [it clearly says](https://developers.home-assistant.io/docs/lovelace_custom_card/). So this means, first I'll update my [README.md](https://github.com/custom-cards/flex-table-card/blob/master/README.md), then I'll try changed it to component for my installation.

For you `component` does not work, is this correct? What do you exactly mean with "does not work", does not show up? no lovelace at all? Could this be a flex-card-configuration "does not work" issue? You are aware about this evil bug here: #5 ... just to make sure we are not accidentally mixing things up here...

**Comment by daringer** [comment] 2020-03-09 08:33
Sooo, I learned various things:
* HACS should show `module` for all flex-card-a-like plugins, thus HACS is right
* the official docs first use 'js' in the first listing and 'module' then in the 2nd, directly pushed a [one-word-PR](https://github.com/home-assistant/developers.home-assistant/pull/430)
* 'js' shall die sooner or later, the plan is to keep 'module' and 'css' 
* the latter means that `flex-table-card` is self-inflicted not working, means I'll have to find out what makes a module :disappointed:

**Comment by daringer** [comment] 2020-03-09 08:41
so that was easy, so please use `module`, will also update the documentation.

**Comment by mdegat01** [comment] 2020-03-09 13:04
Yep, this worked.  Prior to this last update when I set type to `module` this is what I saw in the UI
<img width="432" alt="Screen Shot 2020-03-09 at 9 00 41 AM" src="https://user-images.githubusercontent.com/2037026/76215280-d14acf00-61e4-11ea-8618-30876c27ffa7.png">

Now I set it to type `module` and I see the card as expected.  Thanks for figuring this out!

**Comment by daringer** [comment] 2020-03-09 13:11
great it's finally clarified, thank you, too... 
closing this issue,
cheers

**Closed by daringer** 2020-03-09 13:11 UTC
Labels: docs, maintaining
