### ISSUE TITLE
Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by engren** [custom-cards/flex-table-card#45] opened 2021-02-03 14:01 UTC
Home Assistant 2021.1.5
flex-table-card var VERSION = "0.6.1";

Installed flex-table-card via HACS. Shows up as expected under repositories and card is enabled but cannot be used.

Throws the following error in the GUI editor;
Cannot read property 'setConfig' of undefined

**Comment by daringer** [comment] 2021-02-04 12:22
Cannot reproduce here, maybe need a homeassistant update, can someone else confirm?

**Comment by engren** [comment] 2021-02-04 12:29
Funnily enough, I upgraded to Home Assistant 2021.2.0 and it started working..

**Comment by daringer** [comment] 2021-02-04 15:42
haha, good to hear, one of my favorite solutions to issues :smile: 
so closing this, thank you

**Closed by daringer** 2021-02-04 15:42 UTC
Labels: bug
